title: My Cybersecurity Projects
description: "Portafolio profesional de proyectos de ciberseguridad."
baseurl: ""
url: "https://tu-usuario.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

markdown: kramdown